[Code-Interperator-Options]
;If you wanted a delay when starting to interpret a program
delay:0

;Disable Update Warnings and Disable Updates overall

UpdatesDisabled:false
UpdateErrorWarningsDisabled:false