[Code-Interperator-Options]
;If you wanted a delay when starting to interpret a program
delay:0

;The path to packages to use
packagePath:

;Disable Update Warnings and Disable Updates overall

UpdatesDisabled:false
UpdateErrorWarningsDisabled:false

;PLEASE dont set this to false, or when running any previously unused statement, it will take time to compile
PreCompBaseCode:true